In [2]:
import json
import requests
from bs4 import BeautifulSoup
import re
from pprint import pprint
import pandas as pd

In [3]:
df = pd.read_csv('Presidential_Elections_Data - 2020.csv')

In [4]:
df

,STATE,TOTAL VOTES,Rep_Votes,Rep_Percent,Rep_EV,Dem_Votes,Dem_Percent,Dem_EV,Others_Votes,Others_Percent,YEAR
0,Alabama,"2,323,282","1,441,170",62.03%,9,"849,624",36.57%,NaN,"32,488",1.40%,2020
1,Alaska,"359,530","189,951",52.83%,3,"153,778",42.77%,NaN,"15,801",4.39%,2020
2,Arizona,"3,387,326","1,661,686",49.06%,NaN,"1,672,143",49.36%,11,"53,497",1.58%,2020
3,Arkansas,"1,219,069","760,647",62.40%,6,"423,932",34.78%,NaN,"34,490",2.83%,2020
4,California,"17,500,881","6,006,429",34.32%,NaN,"11,110,250",63.48%,55,"384,202",2.20%,2020
...,...,...,...,...,...,...,...,...,...,...,...
309,Virginia,"2,739,447","1,437,490",52.5,13,"1,217,290",44.4,NaN,"59,398",2.2,2000
310,Washington,"2,487,433","1,108,864",44.6,NaN,"1,247,652",50.2,11,"103,002",4.1,2000
311,West Virginia,"648,124","336,475",51.9,5,"295,497",45.6,NaN,"10,680",1.6,2000
312,Wisconsin,"2,598,607","1,237,279",47.6,NaN,"1,242,987",47.8,11,"94,070",3.6,2000
313,Wyoming,"218,351","147,947",67.8,3,"60,481",27.7,NaN,"4,625",2.1,2000

In [5]:
df = df.replace(to_replace=r'\*$', value='', regex=True)

df['Rep_Percent'] = pd.to_numeric(df['Rep_Percent'].str.rstrip('%'))
df['Dem_Percent'] = pd.to_numeric(df['Dem_Percent'].str.rstrip('%'))

df['Victory_Margin'] = df.apply(lambda row: abs(row['Rep_Percent'] - row['Dem_Percent']), axis=1)
df['Victory_Margin'] = df['Victory_Margin'].round(2)

In [6]:
df

,STATE,TOTAL VOTES,Rep_Votes,Rep_Percent,Rep_EV,Dem_Votes,Dem_Percent,Dem_EV,Others_Votes,Others_Percent,YEAR,Victory_Margin
0,Alabama,"2,323,282","1,441,170",62.03,9,"849,624",36.57,NaN,"32,488",1.40%,2020,25.46
1,Alaska,"359,530","189,951",52.83,3,"153,778",42.77,NaN,"15,801",4.39%,2020,10.06
2,Arizona,"3,387,326","1,661,686",49.06,NaN,"1,672,143",49.36,11,"53,497",1.58%,2020,0.30
3,Arkansas,"1,219,069","760,647",62.40,6,"423,932",34.78,NaN,"34,490",2.83%,2020,27.62
4,California,"17,500,881","6,006,429",34.32,NaN,"11,110,250",63.48,55,"384,202",2.20%,2020,29.16
...,...,...,...,...,...,...,...,...,...,...,...,...
309,Virginia,"2,739,447","1,437,490",52.50,13,"1,217,290",44.40,NaN,"59,398",2.2,2000,8.10
310,Washington,"2,487,433","1,108,864",44.60,NaN,"1,247,652",50.20,11,"103,002",4.1,2000,5.60
311,West Virginia,"648,124","336,475",51.90,5,"295,497",45.60,NaN,"10,680",1.6,2000,6.30
312,Wisconsin,"2,598,607","1,237,279",47.60,NaN,"1,242,987",47.80,11,"94,070",3.6,2000,0.20
313,Wyoming,"218,351","147,947",67.80,3,"60,481",27.70,NaN,"4,625",2.1,2000,40.10

In [7]:
df.to_csv('Presidential_Elections_With_Victory_Margins.csv', index=False)

In [8]:
def calculate_weighted_score(row):
    if row['YEAR'] == 2020:
        return row['Victory_Margin'] * 50
    elif row['YEAR'] == 2016:
        return row['Victory_Margin'] * 25
    elif row['YEAR'] == 2012:
        return row['Victory_Margin'] * 12.5
    elif row['YEAR'] == 2008:
        return row['Victory_Margin'] * 6.25
    elif row['YEAR'] == 2004:
        return row['Victory_Margin'] * 3.125
    elif row['YEAR'] == 2000:
        return row['Victory_Margin'] * 1.5625

# Apply the function to add the 'Weighted_Score' column
df['Weighted_Score'] = df.apply(calculate_weighted_score, axis=1).round(2)

df.head(20)

,STATE,TOTAL VOTES,Rep_Votes,Rep_Percent,Rep_EV,Dem_Votes,Dem_Percent,Dem_EV,Others_Votes,Others_Percent,YEAR,Victory_Margin,Weighted_Score
0,Alabama,"2,323,282","1,441,170",62.03,9,"849,624",36.57,NaN,"32,488",1.40%,2020,25.46,1273.0
1,Alaska,"359,530","189,951",52.83,3,"153,778",42.77,NaN,"15,801",4.39%,2020,10.06,503.0
2,Arizona,"3,387,326","1,661,686",49.06,NaN,"1,672,143",49.36,11,"53,497",1.58%,2020,0.30,15.0
3,Arkansas,"1,219,069","760,647",62.40,6,"423,932",34.78,NaN,"34,490",2.83%,2020,27.62,1381.0
4,California,"17,500,881","6,006,429",34.32,NaN,"11,110,250",63.48,55,"384,202",2.20%,2020,29.16,1458.0
5,Colorado,"3,256,952","1,364,607",41.90,NaN,"1,804,352",55.40,9,"87,993",2.70%,2020,13.50,675.0
6,Connecticut,"1,824,280","715,291",39.21,NaN,"1,080,680",59.24,7,"28,309",1.55%,2020,20.03,1001.5
7,Delaware,"504,010","200,603",39.80,NaN,"296,268",58.78,3,"7,139",1.42%,2020,18.98,949.0
8,District of Columbia,"344,356","18,586",5.40,NaN,"317,323",92.15,3,"8,447",2.45%,2020,86.75,4337.5
9,Florida,"11,067,456","5,668,731",51.22,29,"5,297,045",47.86,NaN,"101,680",0.92%,2020,3.36,168.0
10,Georgia,"4,997,716","2,461,854",49.26,NaN,"2,473,633",49.50,16,"62,229",1.25%,2020,0.24,12.0
11,Hawaii,"574,469","196,864",34.27,NaN,"366,130",63.73,4,"11,475",2.00%,2020,29.46,1473.0
12,Idaho,"868,014","554,119",63.84,4,"287,021",33.07,NaN,"26,874",3.10%,2020,30.77,1538.5
13,Illinois,"6,033,744","2,446,891",40.55,NaN,"3,471,915",57.54,20,"114,938",1.90%,2020,16.99,849.5
14,Indiana,"3,033,121","1,729,519",57.02,11,"1,242,416",40.96,NaN,"61,186",2.02%,2020,16.06,803.0
15,Iowa,"1,690,871","897,672",53.09,6,"759,061",44.89,NaN,"34,138",2.02%,2020,8.20,410.0
16,Kansas,"1,372,303","771,406",56.21,6,"570,323",41.56,NaN,"30,574",2.23%,2020,14.65,732.5
17,Kentucky,"2,136,768","1,326,646",62.09,8,"772,474",36.15,NaN,"37,648",1.76%,2020,25.94,1297.0
18,Louisiana,"2,148,062","1,255,776",58.46,8,"856,034",39.85,NaN,"36,252",1.69%,2020,18.61,930.5
19,Maine,"819,461","360,737",44.02,NaN,"435,072",53.09,2,"23,652",2.89%,2020,9.07,453.5

In [9]:
df_sorted = df.sort_values(by='Weighted_Score', ascending=True)

df_sorted

,STATE,TOTAL VOTES,Rep_Votes,Rep_Percent,Rep_EV,Dem_Votes,Dem_Percent,Dem_EV,Others_Votes,Others_Percent,YEAR,Victory_Margin,Weighted_Score
272,Florida,"5,963,110","2,912,790",48.80,25,"2,912,253",48.80,NaN,"97,488",1.6,2000,0.00,0.00
294,New Mexico,"598,605","286,417",47.80,NaN,"286,783",47.90,5,"21,251",3.6,2000,0.10,0.16
312,Wisconsin,"2,598,607","1,237,279",47.60,NaN,"1,242,987",47.80,11,"94,070",3.6,2000,0.20,0.31
278,Iowa,"1,315,563","634,373",48.20,NaN,"638,517",48.50,7,"29,374",2.2,2000,0.30,0.47
186,Missouri,"2,925,205","1,445,814",49.40,11,"1,441,911",49.30,NaN,NaN,NaN,2008,0.10,0.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,West Virginia,"794,652","545,382",68.63,5,"235,984",29.70,NaN,"13,286",1.67%,2020,38.93,1946.50
55,Wyoming,"276,765","193,559",69.94,3,"73,491",26.55,NaN,"9,715",3.51%,2020,43.39,2169.50
64,Dist. of Col.,"311,268","12,723",4.10,NaN,"282,830",90.90,3,"4,906",1.60%,2016,86.80,2170.00
32,CD-3,"294,831","222,179",75.36,1,"65,854",22.34,NaN,"6,798",2.31%,2020,53.02,2651.00
8,District of Columbia,"344,356","18,586",5.40,NaN,"317,323",92.15,3,"8,447",2.45%,2020,86.75,4337.50

In [10]:
df_sorted.to_csv('Presidential_Elections_With_Weighted_Scores.csv', index=False)

In [11]:
# Determine the winning party for each state and year based on the Rep_Votes and Dem_Votes columns
df['Winner'] = df.apply(lambda row: 'Republicans' if row['Rep_Votes'] > row['Dem_Votes'] else 'Democrats', axis=1)

# Initialize the Flip Points column to 0.0 for all rows
df['Flip Points'] = 0.0

# Define the pairs of years to compare and the respective Flip Points values for each comparison
years_to_compare = [(2020, 2016, 50), (2016, 2012, 25), (2012, 2008, 12.5), (2008, 2004, 6.25), (2004, 2000, 3.125)]

# For each pair of years, check if the state has flipped and assign Flip Points
for year_current, year_previous, points in years_to_compare:
    # Filter the dataframe for the current and previous years
    df_current = df[df['YEAR'] == year_current]
    df_previous = df[df['YEAR'] == year_previous]
    
    # Merge the current and previous dataframes on STATE to compare the winners
    merged = df_current[['STATE', 'Winner']].merge(df_previous[['STATE', 'Winner']], on='STATE', suffixes=('_current', '_previous'))
    
    # Determine if a state has flipped by comparing the winners of the current and previous years
    merged['Flipped'] = merged['Winner_current'] != merged['Winner_previous']
    
    # For each state that has flipped, assign the appropriate Flip Points in the original dataframe
    for state, flipped in zip(merged['STATE'], merged['Flipped']):
        if flipped:
            df.loc[(df['YEAR'] == year_current) & (df['STATE'] == state), 'Flip Points'] = points

# Calculate the sum of Flip Points for each state
Flip_Score = df.groupby('STATE')['Flip Points'].sum().reset_index()

# Sort the states by the sum of their Flip Points in descending order
Flip_Score_sorted = Flip_Score.sort_values(by='Flip Points', ascending=False)

# Display the sorted Flip Score dataframe
Flip_Score_sorted

                   STATE  Flip Points
4                   CD-1      100.000
5                   CD-2      100.000
38          North Dakota       78.125
42          Pennsylvania       75.000
53             Wisconsin       75.000
26              Michigan       75.000
46             Tennessee       65.625
2                Arizona       59.375
49               Vermont       56.250
44        South Carolina       56.250
14               Georgia       50.000
9            Connecticut       50.000
40              Oklahoma       50.000
7             California       50.000
41                Oregon       43.750
19                  Iowa       34.375
13               Florida       31.250
39                  Ohio       31.250
37        North Carolina       18.750
18               Indiana       12.500
35            New Mexico        9.375
24              Maryland        9.375
11         Dist. of Col.        6.250
8               Colorado        6.250
32                Nevada        6.250
50              Virginia        6.250
1                 Alaska        3.125
25         Massachusetts        3.125
33         New Hampshire        3.125
22             Louisiana        3.125
21              Kentucky        3.125
0                Alabama        3.125
48                  Utah        0.000
47                 Texas        0.000
43          Rhode Island        0.000
51            Washington        0.000
45          South Dakota        0.000
52         West Virginia        0.000
27             Minnesota        0.000
36              New York        0.000
34            New Jersey        0.000
31              Nebraska        0.000
30               Montana        0.000
29              Missouri        0.000
28           Mississippi        0.000
23                 Maine        0.000
20                Kansas        0.000
17              Illinois        0.000
16                 Idaho        0.000
15                Hawaii        0.000
12  District of Columbia        0.000
10              Delaware        0.000
6                   CD-3        0.000
3               Arkansas        0.000
54               Wyoming        0.000

In [12]:
Flip_Score_sorted.to_csv('Flip_Score_Sorted.csv', index=False)

In [13]:
flip_score_top_states = pd.read_csv('Flip_Score_Top_12_States.csv')

In [14]:
flip_score_top_states

    Rank           State  Flip Score
0      1    North Dakota      78.125
1      2    Pennsylvania      75.000
2      2       Wisconsin      75.000
3      2        Michigan      75.000
4      5       Tennessee      65.625
5      6         Arizona      59.375
6      7         Vermont      56.250
7      7  South Carolina      56.250
8      9         Georgia      50.000
9      9     Connecticut      50.000
10     9        Oklahoma      50.000
11     9      California      50.000

In [16]:
flip_score_top_states['Flip Score'] = flip_score_top_states['Flip Score'].round(2)

flip_score_top_states

    Rank           State  Flip Score
0      1    North Dakota       78.12
1      2    Pennsylvania       75.00
2      2       Wisconsin       75.00
3      2        Michigan       75.00
4      5       Tennessee       65.62
5      6         Arizona       59.38
6      7         Vermont       56.25
7      7  South Carolina       56.25
8      9         Georgia       50.00
9      9     Connecticut       50.00
10     9        Oklahoma       50.00
11     9      California       50.00

In [17]:
import altair as alt

In [23]:
flip_score_df_sorted = flip_score_top_states.sort_values(by='Flip Score', ascending=False)

ordered_states = flip_score_df_sorted['State'].tolist()

chart = alt.Chart(flip_score_df_sorted).mark_bar().encode(
    x=alt.X('State:N', sort=ordered_states),
    y='Flip Score:Q'
).properties(
    title='Flip Score by State',
    width=780  # Set the width to 780 pixels
)

chart.display()

alt.Chart(...)